# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
          release-notes.yml
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/docker-test.yml
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/render-site.yml
      - source: config_automation.yml
        dest: config_automation.yml
  # Repositories to receive changes
    repos: |
      jhudsl/ottr-website
      jhudsl/Baltimore_Community_Course
###ADD NEW REPO HERE following the format above#

### These are custom groups for syncing -- not all files needs to be synced # will update later
  # - files:
  #   - source: config_automation.yml
  #     dest: config_automation.yml
  #   - source: .github/workflows/pull-request.yml
  #     dest: .github/workflows/pull-request.yml
  #   - source: scripts/spell-check.R
  #     dest: scripts/spell-check.R
  #   repos: |
  #     jhudsl/Baltimore_Community_Course
